#!/bin/bash
echo "Loading..."
date > "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
echo "Currently connected:" >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
w >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
echo "Last logins:" >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
last -a |head -3 >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
echo "Disk and Memory:" >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
df -h | xargs | awk '{print "Free/total disk: " $11 " / " $9}' >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
free -m | xargs | awk '{print "Free/total memory: " $17 " / " $8 " MB"}' >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
echo "CPU:" >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
top -b |head -3 >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
echo "Current connections:" >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
ss -s >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
echo "Processes:" >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
ps auxf --width=200 >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
echo "vmstat:" >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
vmstat 1 5 >> "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
less "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"
rm "SCROLL UP AND DOWN TO EVALUATE (Q TO EXIT)"